const chapterNameMap = {
  'National Chengchi University': '國立政治大學',
  'National Tsing Hua University': '國立清華大學',
  'National Taiwan University': '國立臺灣大學',
  'National Taiwan Normal University': '國立臺灣師範大學',
  'National Cheng Kung University': '國立成功大學',
  'National Chung Hsing University': '國立中興大學',
  'National Central University': '國立中央大學',
  'National Sun Yat-sen University': '國立中山大學',
  'National Taiwan Ocean University': '國立臺灣海洋大學',
  'National Chung Cheng University': '國立中正大學',
  'National Kaohsiung Normal University': '國立高雄師範大學',
  'National Changhua University of Education': '國立彰化師範大學',
  'National Yang Ming Chiao Tung University': '國立陽明交通大學',
  'National Taipei University': '國立臺北大學',
  'National Chiayi University': '國立嘉義大學',
  'National University of Kaohsiung': '國立高雄大學',
  'National Dong Hwa University': '國立東華大學',
  'National Chi Nan University': '國立暨南國際大學',
  'National Taiwan University of Science and Technology': '國立臺灣科技大學',
  'National Yunlin University of Science and Technology': '國立雲林科技大學',
  'National Pingtung University of Science and Technology': '國立屏東科技大學',
  'National Taipei University of Technology': '國立臺北科技大學',
  'National Taipei University of the Arts': '國立臺北藝術大學',
  'Tainan National University of the Arts': '國立臺南藝術大學',
  'National Taitung University': '國立臺東大學',
  'National Ilan University': '國立宜蘭大學',
  'National United University': '國立聯合大學',
  'National Formosa University': '國立虎尾科技大學',
  'National University of Tainan': '國立臺南大學',
  'National Taipei University of Education': '國立臺北教育大學',
  'National Taichung University of Education': '國立臺中教育大學',
  'National Penghu University of Science and Technology': '國立澎湖科技大學',
  'National Chin-Yi University of Technology': '國立勤益科技大學',
  'National Taiwan Sport University': '國立體育大學',
  'National Taipei University of Nursing and Health Sciences': '國立臺北護理健康大學',
  'National Kaohsiung University of Hospitality and Tourism': '國立高雄餐旅大學',
  'National Quemoy University': '國立金門大學',
  'National Taiwan University of Sport': '國立臺灣體育運動大學',
  'National Taichung University of Science and Technology': '國立臺中科技大學',
  'National Taipei University of Business': '國立臺北商業大學',
  'National Pingtung University': '國立屏東大學',
  'National Kaohsiung University of Science and Technology': '國立高雄科技大學',
  'National Taiwan College of Performing Arts': '國立臺灣戲曲學院',
  'National Tainan Junior College of Nursing': '國立臺南護理專科學校',
  'National Taitung Junior College': '國立臺東專科學校',
  'National Open University': '國立空中大學',
  'Tunghai University': '東方設計大學',
  'Fooyin University': '輔英科技大學',
  'Soochow University': '東吳大學',
  'Chung Yuan Christian University': '中原大學',
  'Tamkang University': '淡江大學',
  'Chinese Culture University': '中國文化大學',
  'Feng Chia University': '逢甲大學',
  'Jingyi University': '靜宜大學',
  'Chang Gung University': '長庚大學',
  'Yuan Ze University': '元智大學',
  'Chung Hua University': '中華大學',
  'Dayeh University': '大葉大學',
  'Huafan University': '華梵大學',
  'I-Shou University': '義守大學',
  'Shih Hsin University': '世新大學',
  'Ming Chuan University': '銘傳大學',
  'Shih Chien University': '實踐大學',
  'Chaoyang University of Technology': '朝陽科技大學',
  'Kaohsiung Medical University': '高雄醫學大學',
  'Nanhua University': '南華大學',
  'Aletheia University': '真理大學',
  'Tatung University': '大同大學',
  'Southern Taiwan University of Science and Technology': '南臺科技大學',
  'Kun Shan University': '崑山科技大學',
  'Chia Nan University of Pharmacy and Science': '嘉南藥理大學',
  'Shu-Te University': '樹德科技大學',
  'Tzu Chi University': '慈濟大學',
  'Taipei Medical University': '臺北醫學大學',
  'Chung Shan Medical University': '中山醫學大學',
  'Lunghwa University of Science and Technology': '龍華科技大學',
  'Minghsin University of Science and Technology': '明新科技大學',
  'Chang Jung Christian University': '長榮大學',
  'Hungkuang University': '弘光科技大學',
  'China Medical University': '中華醫事科技大學',
  'Chien Hsin University of Science and Technology': '健行科技大學',
  'Cheng Shiu University': '正修科技大學',
  'Vanung University': '萬能科技大學',
  'Hsuan Chuang University': '玄奘大學',
  'Chienkuo Technology University': '建國科技大學',
  'Ming Chi University of Technology': '明志科技大學',
  'Kao Yuan University': '高苑科技大學',
  'Daren University': '大仁科技大學',
  "St. John's University of Science and Technology": '聖約翰科技大學',
  'Ling Tung University of Science and Technology': '嶺東科技大學',
  'China University of Technology': '中國科技大學',
  'Chungtai Institute of Health Sciences and Technology': '中臺科技大學',
  'Asia University': '亞洲大學',
  'Kainan University': '開南大學',
  'Fo Guang University': '佛光大學',
  'Tainan University of Applied Sciences': '台南應用科技大學',
  'Far East University': '遠東科技大學',
  'Yuanpei University of Medical Technology': '元培醫事科技大學',
  'Jingwen University of Science and Technology': '景文科技大學',
  'Tungnan University': '東南科技大學',
  'Takming University of Science and Technology': '德明財經科技大學',
  'MingDao University': '明道大學',
  'Nan Kai University of Technology': '南開科技大學',
  'China University of Science and Technology': '中華科技大學',
  'Chiao Kuo University of Technology': '僑光科技大學',
  'Yu Da University': '育達科技大學',
  'Meiho University': '美和科技大學',
  'Wufeng University': '吳鳳科技大學',
  'Global University': '環球科技大學',
  'Taiwan Shoufu University': '台灣首府大學',
  'Chung Chou University of Science and Technology': '中州科技大學',
  'Hsiuping University of Science and Technology': '修平科技大學',
  'Chang Gung University of Science and Technology': '長庚科技大學',
  'Taipei Chengshih University of Science and Technology': '臺北城市科技大學',
  'Tahwa Institute of Technology': '大華科技大學',
  'Hsing Wu University': '醒吾科技大學',
  'Wenzao Ursuline University of Languages': '文藻外語大學',
  'Huaxia University': '華夏科技大學',
  'Tzu Chi University of Science and Technology': '慈濟科技大學',
  'Chihlee University of Technology': '致理科技大學',
  'Kangning University': '康寧大學',
  'Hungkuo Delin University of Technology': '宏國德霖科技大學',
  'Chungyu University of Film and Arts': '崇右影藝科技大學',
  'Taipei Marine University': '台北海洋科技大學',
  'CTBC Financial Management College': '中信金融管理學院',
  'Tahan Junior College of Technology': '大漢技術學院',
  'HeChun Junior College of Technology': '和春技術學院',
  'Asia University of Science and Technology': '亞東技術學院',
  'Nanya Institute of Technology': '南亞技術學院',
  'Da-Jiang Institute of Technology and Management': '稻江科技暨管理學院',
  'Lan Yang Institute of Technology': '蘭陽技術學院',
  'Li-Ming Institute of Technology': '黎明技術學院',
  'Ching Kuo Institute of Management and Health': '經國管理暨健康學院',
  'Da Tong Institute of Technology': '大同技術學院',
  'Taiwan Hospitality and Tourism College': '臺灣觀光學院',
  'Mackay Medical College': '馬偕醫學院',
  'Dharma Drum Institute of Liberal Arts': '法鼓文理學院',
  'Mackay Medicine, Nursing and Management College': '馬偕醫護管理專科學校',
  'Jen-Teh Junior College of Medicine, Nursing and Management': '仁德醫護管理專科學校',
  'Shu-Zen Junior College of Medicine and Management': '樹人醫護管理專科學校',
  'Tzu Chi College of Nursing and Health Sciences': '慈濟醫護管理專科學校',
  'Keng Seng College of Nursing and Medical Care': '耕莘健康管理專科學校',
  'Min-Hwei College of Health Care Management': '敏惠醫護管理專科學校',
  'Yu-Ying College of Vocational Nursing': '育英醫護管理專科學校',
  "Holy Family College of Nursing and St. Mary's Junior College of Medicine, Nursing, and Management": '聖母醫護管理專科學校',
  'Shin Sheng College of Medical Care and Management for Women and Infants': '新生醫護管理專科學校',
  'Chung Jen College of Nursing, Health Science and Management': '崇仁醫護管理專科學校',
  'Taiwan Baptist Christian College': '中華浸信會基督教台灣浸會神學院',
  'Taipei Christian University': '臺北基督學院',
  'I-Kuan Tao Emperor Hsuan College': '財團法人一貫道天皇基金會一貫道天皇學院',
  'Taiwan Theological College and Seminary': '台灣基督長老教會南神神學院',
  'I-Kuan Tao Institute of Moral Education': '一貫道崇德學院',
  'University of Taipei': '臺北市立大學',
  'Kao Yuan University of Science and Technology': '高雄市立空中大學',
  "National Dong Hwa University (Hualien University of Education)":"國立東華大學",
  "Taipei University of Technology":"國立臺北科技大學",
  "Fu Jen Catholic University":"輔仁大學"
}
export default chapterNameMap;